/**
 * The vendored `.ores-lint/` tree is generated by a fleet rollout, and a
 * rollout that copies an incomplete file list produces a toolkit that cannot
 * run its own guard: `selftest.sh` called `$DIR/require-send.test.mjs`,
 * `$DIR/eslint/plugin.test.mjs` and `$DIR/tests/integration.mjs` while none of
 * the three were shipped, so the self-test failed on a pristine checkout and
 * the ores-lint baseline was effectively unguarded.
 *
 * This test closes that hole: every path the shipped scripts reference must be
 * a file that is actually present in the vendored set. A future rollout can no
 * longer ship a manifest that names a file it does not include.
 */

import assert from 'node:assert/strict';
import { readFile, readdir, stat } from 'node:fs/promises';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const toolkit = path.resolve(here, '..', '.ores-lint');

async function walk(dir, prefix = '') {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) out.push(...await walk(path.join(dir, entry.name), rel));
    else if (entry.isFile()) out.push(rel);
  }
  return out;
}

const shipped = await walk(toolkit);
const shippedSet = new Set(shipped);

/** `$DIR/foo`, `"$DIR/foo"` and `${DIR}/foo` as written by the shell scripts. */
const DIR_REF = /\$\{?DIR\}?\/([A-Za-z0-9._/-]+)/g;
/** Relative ESM specifiers inside the vendored .mjs files. */
const IMPORT_REF = /(?:^|\n)\s*import[^'"\n]*from\s+['"](\.[^'"]+)['"]/g;

async function references() {
  const found = [];
  for (const rel of shipped) {
    if (!/\.(sh|mjs)$/.test(rel)) continue;
    const text = await readFile(path.join(toolkit, rel), 'utf8');
    for (const [, target] of text.matchAll(DIR_REF)) found.push({ from: rel, target });
    if (rel.endsWith('.mjs')) {
      for (const [, spec] of text.matchAll(IMPORT_REF)) {
        const target = path.posix.normalize(path.posix.join(path.posix.dirname(rel), spec));
        found.push({ from: rel, target });
      }
    }
  }
  return found;
}

test('the vendored toolkit is not missing files it was shipped with', () => {
  for (const required of ['VERSION', 'config.sh', 'lint.sh', 'selftest.sh', 'require-send.mjs']) {
    assert.ok(shippedSet.has(required), `.ores-lint/${required} is missing from the rollout`);
  }
});

test('every path the ores-lint scripts reference is actually shipped', async () => {
  const missing = [];
  for (const { from, target } of await references()) {
    // Directories the scripts probe for rather than depend on.
    if (target.endsWith('/')) continue;
    // Optional, deliberately absent: local.sh is the per-repo override the
    // rollout never writes, and test-tools/ is an opt-in local ESLint install.
    if (target === 'local.sh' || target.startsWith('test-tools/')) continue;
    if (!shippedSet.has(target)) missing.push(`${from} -> .ores-lint/${target}`);
  }
  assert.deepEqual(
    missing,
    [],
    `.ores-lint references files that the rollout did not ship:\n  ${missing.join('\n  ')}`,
  );
});

test('the self-test fixtures exist and are non-trivial', async () => {
  for (const fixture of [
    'require-send.test.mjs',
    'eslint/plugin.test.mjs',
    'tests/integration.mjs',
  ]) {
    assert.ok(shippedSet.has(fixture), `.ores-lint/${fixture} is missing`);
    const info = await stat(path.join(toolkit, fixture));
    assert.ok(info.size > 200, `.ores-lint/${fixture} looks like a stub (${info.size} bytes)`);
  }
});

test('the vendored eslint plugin version tracks the toolkit VERSION', async () => {
  const version = (await readFile(path.join(toolkit, 'VERSION'), 'utf8')).trim();
  const plugin = await import(path.join(toolkit, 'eslint', 'plugin.mjs'));
  assert.equal(plugin.default.meta.version, version);
});

test('selftest.sh still runs each fixture it ships', async () => {
  const selftest = await readFile(path.join(toolkit, 'selftest.sh'), 'utf8');
  assert.match(selftest, /require-send\.test\.mjs/);
  assert.match(selftest, /eslint\/plugin\.test\.mjs/);
  assert.match(selftest, /tests\/integration\.mjs/);
});
