#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { lstat, readFile, readdir } from 'node:fs/promises';
import { dirname, isAbsolute, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
const here=dirname(fileURLToPath(import.meta.url));const root=resolve(here,'..');const manifestPath=resolve(here,'manifest.v1.json');
const fail=m=>{console.error(`[conformance] ${m}`);process.exitCode=1;};
const ensureRelative=(v,l)=>{if(typeof v!=='string'||!v||isAbsolute(v))throw new Error(`${l} must be a non-empty repository-relative path`);const r=resolve(root,v),rel=relative(root,r);if(rel==='..'||rel.startsWith(`..${sep}`)||isAbsolute(rel))throw new Error(`${l} escapes the repository root: ${v}`);return{resolved:r};};
const collectFiles=async p=>{const{resolved}=ensureRelative(p,'root');const rs=await lstat(resolved);if(rs.isSymbolicLink())throw new Error(`symlink root is forbidden: ${p}`);if(!rs.isDirectory())throw new Error(`root is not a directory: ${p}`);const files=[];const walk=async d=>{const es=await readdir(d,{withFileTypes:true});es.sort((a,b)=>a.name.localeCompare(b.name));for(const e of es){const f=resolve(d,e.name),rel=relative(root,f).split(sep).join('/'),s=await lstat(f);if(s.isSymbolicLink())throw new Error(`symlink is forbidden in conformance inputs: ${rel}`);if(s.isDirectory())await walk(f);else if(s.isFile())files.push({full:f,rel});}};await walk(resolved);return files;};
const digestFiles=async fs=>{const h=createHash('sha256');for(const f of[...fs].sort((a,b)=>a.rel.localeCompare(b.rel))){h.update(f.rel);h.update(Buffer.from([0]));h.update(await readFile(f.full));h.update(Buffer.from([0]));}return h.digest('hex');};
try{const m=JSON.parse(await readFile(manifestPath,'utf8'));if(m.schema!=='ores.conformance.manifest/v1')throw new Error('manifest schema must be ores.conformance.manifest/v1');if(!['bootstrap','enforced'].includes(m.coverageStatus))throw new Error('coverageStatus must be bootstrap or enforced');if(!Array.isArray(m.contractRoots)||!m.contractRoots.length)throw new Error('contractRoots must be a non-empty array');if(!Array.isArray(m.caseRoots)||!m.caseRoots.length)throw new Error('caseRoots must be a non-empty array');if(!Array.isArray(m.requiredParticipants))throw new Error('requiredParticipants must be an array');const cfs=(await Promise.all(m.contractRoots.map(collectFiles))).flat(),cases=(await Promise.all(m.caseRoots.map(collectFiles))).flat();if(!cases.length)throw new Error('conformance corpus is empty');const ids=new Set();for(const f of cases){if(!f.rel.endsWith('.json'))throw new Error(`case roots may contain only JSON files: ${f.rel}`);const v=JSON.parse(await readFile(f.full,'utf8'));if(!v||Array.isArray(v)||typeof v!=='object'||typeof v.schema!=='string'||!v.schema||typeof v.id!=='string'||!v.id)throw new Error(`case requires string schema and id: ${f.rel}`);const id=`${v.schema}\u0000${v.id}`;if(ids.has(id))throw new Error(`duplicate case identity ${v.schema}:${v.id}`);ids.add(id);}const contractsSha256=await digestFiles(cfs),corpusSha256=await digestFiles(cases),pids=new Set();for(const p of m.requiredParticipants){if(!p||typeof p.id!=='string'||!p.id)throw new Error('every required participant must have a non-empty string id');if(pids.has(p.id))throw new Error(`duplicate participant id: ${p.id}`);pids.add(p.id);}if(m.coverageStatus==='enforced'){if(!m.requiredParticipants.length)throw new Error('enforced coverage requires at least one required participant');const{resolved:ed}=ensureRelative(m.evidenceDir,'evidenceDir');for(const p of m.requiredParticipants){const e=JSON.parse(await readFile(resolve(ed,`${p.id}.json`),'utf8'));if(e.schema!=='ores.conformance.evidence/v1'||e.participant!==p.id||e.contractsSha256!==contractsSha256||e.corpusSha256!==corpusSha256)throw new Error(`invalid or stale evidence for ${p.id}`);}}console.log(JSON.stringify({schema:'ores.conformance.check/v1',coverageStatus:m.coverageStatus,contractFileCount:cfs.length,caseFileCount:cases.length,contractsSha256,corpusSha256,requiredParticipants:m.requiredParticipants.map(({id})=>id)},null,2));}catch(e){fail(e instanceof Error?e.message:String(e));}
