apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: ores-otel-sidecar-v1
    files:
      - config.yaml=collector.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: ores-otel-sidecar
    app.kubernetes.io/part-of: ores-otel
    app.kubernetes.io/version: "0.1.0"
